In [1]:
import numpy as np

In [10]:
%%time
l = list(range(10))
l

CPU times: user 25 µs, sys: 1e+03 ns, total: 26 µs
Wall time: 31 µs


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [11]:
np.array(l)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
%%time
l = list(range(10))
np.mean(l)

CPU times: user 213 µs, sys: 160 µs, total: 373 µs
Wall time: 378 µs


4.5

In [14]:
l = np.array(l)
l

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
%%time
np.mean(l)

CPU times: user 123 µs, sys: 1 µs, total: 124 µs
Wall time: 129 µs


4.5

In [16]:
help(np.full)

Help on function full in module numpy:

full(shape, fill_value, dtype=None, order='C', *, like=None)
    Return a new array of given shape and type, filled with `fill_value`.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    fill_value : scalar or array_like
        Fill value.
    dtype : data-type, optional
        The desired data-type for the array  The default, None, means
         ``np.array(fill_value).dtype``.
    order : {'C', 'F'}, optional
        Whether to store multidimensional data in C- or Fortran-contiguous
        (row- or column-wise) order in memory.
    like : array_like
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that pas

In [39]:
np.full((5,3),[1,5,7])

array([[1, 5, 7],
       [1, 5, 7],
       [1, 5, 7],
       [1, 5, 7],
       [1, 5, 7]])

In [19]:
help(np.arange)

Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None, *, like=None)
    
    Return evenly spaced values within a given interval.
    
    Values are generated within the half-open interval ``[start, stop)``
    (in other words, the interval including `start` but excluding `stop`).
    For integer arguments the function is equivalent to the Python built-in
    `range` function, but returns an ndarray rather than a list.
    
    When using a non-integer step, such as 0.1, the results will often not
    be consistent.  It is better to use `numpy.linspace` for these cases.
    
    Parameters
    ----------
    start : integer or real, optional
        Start of interval.  The interval includes this value.  The default
        start value is 0.
    stop : integer or real
        End of interval.  The interval does not include this value, except
        in some cases where `step` is not an integer and floating point
        round-off 

In [22]:
np.arange(100,110,step=3)

array([100, 103, 106, 109])

In [23]:
help(np.linspace)

Help on function linspace in module numpy:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.
    
    .. versionchanged:: 1.20.0
        Values are rounded towards ``-inf`` instead of ``0`` when an
        integer ``dtype`` is specified. The old behavior can
        still be obtained with ``np.linspace(start, stop, num).astype(int)``
    
    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that 

In [24]:
help(np.zeros)

Help on built-in function zeros in module numpy:

zeros(...)
    zeros(shape, dtype=float, order='C', *, like=None)
    
    Return a new array of given shape and type, filled with zeros.
    
    Parameters
    ----------
    shape : int or tuple of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    like : array_like
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this argument.
   

In [26]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [31]:
x = np.zeros((10,10,10))

In [33]:
x.shape

(10, 10, 10)

In [32]:
x.ndim

3

In [34]:
x.dtype

dtype('float64')

In [43]:
l = list(range(1,10))
l = [i*2 for i in l]
l
np.sqrt(l)

array([1.41421356, 2.        , 2.44948974, 2.82842712, 3.16227766,
       3.46410162, 3.74165739, 4.        , 4.24264069])

In [44]:
help(np.dot)

Help on function dot in module numpy:

dot(...)
    dot(a, b, out=None)
    
    Dot product of two arrays. Specifically,
    
    - If both `a` and `b` are 1-D arrays, it is inner product of vectors
      (without complex conjugation).
    
    - If both `a` and `b` are 2-D arrays, it is matrix multiplication,
      but using :func:`matmul` or ``a @ b`` is preferred.
    
    - If either `a` or `b` is 0-D (scalar), it is equivalent to :func:`multiply`
      and using ``numpy.multiply(a, b)`` or ``a * b`` is preferred.
    
    - If `a` is an N-D array and `b` is a 1-D array, it is a sum product over
      the last axis of `a` and `b`.
    
    - If `a` is an N-D array and `b` is an M-D array (where ``M>=2``), it is a
      sum product over the last axis of `a` and the second-to-last axis of `b`::
    
        dot(a, b)[i,j,k,m] = sum(a[i,j,:] * b[k,:,m])
    
    Parameters
    ----------
    a : array_like
        First argument.
    b : array_like
        Second argument.
    out : 

In [50]:
help(np.equal)

Help on ufunc:

equal = <ufunc 'equal'>
    equal(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Return (x1 == x2) element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        Input arrays.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

In [56]:
a = np.full((2,3),5)
b = np.full((2,2),5)
np.array_equal(a,b)

False

In [72]:
help(np.corrcoef)

Help on function corrcoef in module numpy:

corrcoef(x, y=None, rowvar=True, bias=<no value>, ddof=<no value>, *, dtype=None)
    Return Pearson product-moment correlation coefficients.
    
    Please refer to the documentation for `cov` for more detail.  The
    relationship between the correlation coefficient matrix, `R`, and the
    covariance matrix, `C`, is
    
    .. math:: R_{ij} = \frac{ C_{ij} } { \sqrt{ C_{ii} * C_{jj} } }
    
    The values of `R` are between -1 and 1, inclusive.
    
    Parameters
    ----------
    x : array_like
        A 1-D or 2-D array containing multiple variables and observations.
        Each row of `x` represents a variable, and each column a single
        observation of all those variables. Also see `rowvar` below.
    y : array_like, optional
        An additional set of variables and observations. `y` has the same
        shape as `x`.
    rowvar : bool, optional
        If `rowvar` is True (default), then each row represents a
        vari

In [134]:
help(np.hstack)

Help on function hstack in module numpy:

hstack(tup)
    Stack arrays in sequence horizontally (column wise).
    
    This is equivalent to concatenation along the second axis, except for 1-D
    arrays where it concatenates along the first axis. Rebuilds arrays divided
    by `hsplit`.
    
    This function makes most sense for arrays with up to 3 dimensions. For
    instance, for pixel-data with a height (first axis), width (second axis),
    and r/g/b channels (third axis). The functions `concatenate`, `stack` and
    `block` provide more general stacking and concatenation operations.
    
    Parameters
    ----------
    tup : sequence of ndarrays
        The arrays must have the same shape along all but the second axis,
        except 1-D arrays which can be any length.
    
    Returns
    -------
    stacked : ndarray
        The array formed by stacking the given arrays.
    
    See Also
    --------
    concatenate : Join a sequence of arrays along an existing axis.
    s

In [133]:
cust_1 = np.array([1, 2, 3])
cust_2 = np.array([4, 5, 6])
np.vstack((cust_1,cust_2))

array([[1, 2, 3],
       [4, 5, 6]])

In [135]:
temp = np.array([20,30,35])
gdp = np.array([20,30,35])

sales = np.array([80,90,105])

In [136]:
np.hstack((temp,gdp))

array([20, 30, 35, 20, 30, 35])

In [139]:
np.column_stack((temp,gdp,sales))

array([[ 20,  20,  80],
       [ 30,  30,  90],
       [ 35,  35, 105]])

In [148]:
help(np.concatenate)

Help on function concatenate in module numpy:

concatenate(...)
    concatenate((a1, a2, ...), axis=0, out=None, dtype=None, casting="same_kind")
    
    Join a sequence of arrays along an existing axis.
    
    Parameters
    ----------
    a1, a2, ... : sequence of array_like
        The arrays must have the same shape, except in the dimension
        corresponding to `axis` (the first, by default).
    axis : int, optional
        The axis along which the arrays will be joined.  If axis is None,
        arrays are flattened before use.  Default is 0.
    out : ndarray, optional
        If provided, the destination to place the result. The shape must be
        correct, matching that of what concatenate would have returned if no
        out argument were specified.
    dtype : str or dtype
        If provided, the destination array will have this dtype. Cannot be
        provided together with `out`.
    
        .. versionadded:: 1.20.0
    
    casting : {'no', 'equiv', 'safe', '

In [213]:
x = np.arange(16.0).reshape(2,8)
x
#np.hsplit(x, 2)

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11., 12., 13., 14., 15.]])

In [214]:
np.hsplit(x, 4)
#help(np.hsplit)

[array([[0., 1.],
        [8., 9.]]),
 array([[ 2.,  3.],
        [10., 11.]]),
 array([[ 4.,  5.],
        [12., 13.]]),
 array([[ 6.,  7.],
        [14., 15.]])]

In [170]:
import numpy as np
a = np.array([[0,0,0],[1,2,3],[4,5,6],[5,6,7]])
b = np.array([[0,1,2]])
print("First Array: \n",a,'\n')
print("Second Array: \n",b,'\n')
print("First Array + Second Array: \n",a+b,'\n')

First Array: 
 [[0 0 0]
 [1 2 3]
 [4 5 6]
 [5 6 7]] 

Second Array: 
 [[0 1 2]] 

First Array + Second Array: 
 [[0 1 2]
 [1 3 5]
 [4 6 8]
 [5 7 9]] 



In [219]:
x[:,:3] * ([1],[2])#,[3]

array([[ 0.,  1.,  2.],
       [16., 18., 20.]])

In [221]:
import numpy as numpy
a = np.arange(9).reshape((3,3))
b = [0,1,2]
c = numpy.diag(b)

c#numpy.dot(c,a)

array([[0, 0, 0],
       [0, 1, 0],
       [0, 0, 2]])

In [191]:
help(np.vectorize)

Help on class vectorize in module numpy:

class vectorize(builtins.object)
 |  vectorize(pyfunc, otypes=None, doc=None, excluded=None, cache=False, signature=None)
 |  
 |  vectorize(pyfunc, otypes=None, doc=None, excluded=None, cache=False,
 |            signature=None)
 |  
 |  Generalized function class.
 |  
 |  Define a vectorized function which takes a nested sequence of objects or
 |  numpy arrays as inputs and returns a single numpy array or a tuple of numpy
 |  arrays. The vectorized function evaluates `pyfunc` over successive tuples
 |  of the input arrays like the python map function, except it uses the
 |  broadcasting rules of numpy.
 |  
 |  The data type of the output of `vectorized` is determined by calling
 |  the function with the first element of the input.  This can be avoided
 |  by specifying the `otypes` argument.
 |  
 |  Parameters
 |  ----------
 |  pyfunc : callable
 |      A python function or method.
 |  otypes : str or list of dtypes, optional
 |      The 

In [202]:
def some_complex_fun(r):
    return r*r

#vfunc = np.vectorize(lambda r:r*2)
vfunc = np.vectorize(some_complex_fun)
#vfunc = np.vectorize(some_complex_fun)
vfunc
l = np.array([1,2,3])
l,vfunc(l)

(array([1, 2, 3]), array([1, 4, 9]))

In [201]:
np.array([1,2,3,4,5]).reshape(5,1) * [1,2,3,4,5]

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

In [203]:
#Numpy vs List: Memory size
import numpy as np
import sys

#define a list
l = range(1000)
print("Size of a list: ",sys.getsizeof(1)*len(l))

#define a numpy array
a = np.arange(1000)
print("Size of an array: ",a.size*a.itemsize)

Size of a list:  28000
Size of an array:  8000


In [205]:
#Numpy vs List: Speed
import time
def using_List():
    t1 = time.time()#Starting/Initial Time
    X = range(10000)
    Y = range(10000)
    z = [X[i]+Y[i] for i in range(len(X))]
    return time.time()-t1

def using_Numpy():
    t1 = time.time()#Starting/Initial Time
    a = np.arange(10000)
    b = np.arange(10000)
    z =a+b #more convient than a list
    return time.time()-t1
list_time = using_List()
numpy_time = using_Numpy()
print(list_time,numpy_time)
print("In this example Numpy is "+str(list_time/numpy_time)+" times faster than a list")

0.006819009780883789 0.0004582405090332031
In this example Numpy is 14.880853277835588 times faster than a list
